# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanas\ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 365)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ventanas\\../iconos/icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_convertir_dolares = QtWidgets.QRadioButton(self.centralwidget)
        self.boton_convertir_dolares.setGeometry(QtCore.QRect(70, 90, 401, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.boton_convertir_dolares.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ventanas\\../iconos/simbolo-dolar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_convertir_dolares.setIcon(icon1)
        self.boton_convertir_dolares.setIconSize(QtCore.QSize(32, 32))
        self.boton_convertir_dolares.setObjectName("boton_convertir_dolares")
        self.grupo_botones = QtWidgets.QButtonGroup(MainWindow)
        self.grupo_botones.setObjectName("grupo_botones")
        self.grupo_botones.addButton(self.boton_convertir_dolares)
        self.boton_convertir_yenes = QtWidgets.QRadioButton(self.centralwidget)
        self.boton_convertir_yenes.setGeometry(QtCore.QRect(70, 130, 381, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.boton_convertir_yenes.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ventanas\\../iconos/simbolo-yen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_convertir_yenes.setIcon(icon2)
        self.boton_convertir_yenes.setIconSize(QtCore.QSize(32, 32))
        self.boton_convertir_yenes.setObjectName("boton_convertir_yenes")
        self.grupo_botones.addButton(self.boton_convertir_yenes)
        self.edit_euros = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_euros.setGeometry(QtCore.QRect(270, 10, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.edit_euros.setFont(font)
        self.edit_euros.setObjectName("edit_euros")
        self.edit_resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_resultado.setEnabled(False)
        self.edit_resultado.setGeometry(QtCore.QRect(270, 50, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.edit_resultado.setFont(font)
        self.edit_resultado.setObjectName("edit_resultado")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(10, 50, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_resultado.setFont(font)
        self.label_resultado.setText("")
        self.label_resultado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_resultado.setObjectName("label_resultado")
        self.boton_convertir_libras = QtWidgets.QRadioButton(self.centralwidget)
        self.boton_convertir_libras.setGeometry(QtCore.QRect(70, 170, 451, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.boton_convertir_libras.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ventanas\\../iconos/simbolo-libra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_convertir_libras.setIcon(icon3)
        self.boton_convertir_libras.setIconSize(QtCore.QSize(32, 32))
        self.boton_convertir_libras.setObjectName("boton_convertir_libras")
        self.grupo_botones.addButton(self.boton_convertir_libras)
        self.boton_convertir_rublos = QtWidgets.QRadioButton(self.centralwidget)
        self.boton_convertir_rublos.setGeometry(QtCore.QRect(70, 210, 451, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.boton_convertir_rublos.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ventanas\\../iconos/simbolo-rublo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_convertir_rublos.setIcon(icon4)
        self.boton_convertir_rublos.setIconSize(QtCore.QSize(32, 32))
        self.boton_convertir_rublos.setObjectName("boton_convertir_rublos")
        self.grupo_botones.addButton(self.boton_convertir_rublos)
        self.boton_convertir_bitcoins = QtWidgets.QRadioButton(self.centralwidget)
        self.boton_convertir_bitcoins.setGeometry(QtCore.QRect(70, 250, 451, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.boton_convertir_bitcoins.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ventanas\\../iconos/simbolo-bitcoin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_convertir_bitcoins.setIcon(icon5)
        self.boton_convertir_bitcoins.setIconSize(QtCore.QSize(32, 32))
        self.boton_convertir_bitcoins.setObjectName("boton_convertir_bitcoins")
        self.grupo_botones.addButton(self.boton_convertir_bitcoins)
        self.boton_borrar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_borrar.setGeometry(QtCore.QRect(155, 300, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.boton_borrar.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ventanas\\../iconos/borrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_borrar.setIcon(icon6)
        self.boton_borrar.setIconSize(QtCore.QSize(32, 32))
        self.boton_borrar.setObjectName("boton_borrar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conversor de monedas"))
        self.boton_convertir_dolares.setText(_translate("MainWindow", "Convertir a Dolares"))
        self.boton_convertir_yenes.setText(_translate("MainWindow", "Convertir a Yenes"))
        self.edit_euros.setText(_translate("MainWindow", "0,00"))
        self.label.setText(_translate("MainWindow", "Cantidad en Euros:"))
        self.boton_convertir_libras.setText(_translate("MainWindow", "Convertir a Libras"))
        self.boton_convertir_rublos.setText(_translate("MainWindow", "Convertir a Rublos"))
        self.boton_convertir_bitcoins.setText(_translate("MainWindow", "Convertir a Bitcoins"))
        self.boton_borrar.setText(_translate("MainWindow", "Limpiar"))
